server:
  port: 8091
eureka:
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true


spring:
  application:
    name: FINANCEIRO
