server:
  port: 0
eureka:
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

spring:
  zipkin:
    base-url: http://44.209.166.240:9411
  application:
    name: FINANCEIRO


